spring:
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true

  datasource:
   url: ${cloud.services.struts-mysql.connection.jdbcurl:jdbc:h2:mem:struts-db}
   username: ${cloud.services.struts-mysql.connection.username:sa}
   password: ${cloud.services.struts-mysql.connection.password:}

struts:
  action:
    packages:
    - com.lq
---
spring:
  profiles: local
  datasource:
    platform: h2
